- name: include env vars
  include_vars: "{{ rbenv.env }}.yml"

- include: apt_build_depends.yml
  when: ansible_pkg_mgr == 'apt'

- name: checkout rbenv_repo for system
  git: >
    repo={{ rbenv_repo }}
    dest={{ rbenv_root }}
    version={{ rbenv.version }}
    accept_hostkey=yes
    force=yes
  tags:
    - rbenv

- name: create plugins directory for system
  file: state=directory path={{ rbenv_root }}/plugins
  tags:
    - rbenv

- name: install plugins for system
  git: >
    repo=https://github.com/rbenv/ruby-build.git
    dest={{ rbenv_root }}/plugins/ruby-build
    accept_hostkey=yes
    force=yes
  tags:
    - rbenv

- name: add rbenv initialization to profile system-wide
  template: src=rbenv.sh.j2 dest=/etc/profile.d/rbenv.sh owner=root group=root mode=0755
  when:
    - ansible_os_family != 'OpenBSD'
  tags:
    - rbenv

- name: check ruby {{ rbenv.ruby_version }} installed for system
  shell: $SHELL -lc "rbenv versions | grep {{ rbenv.ruby_version }}"
  register: ruby_installed
  changed_when: false
  ignore_errors: yes
  always_run: yes
  when: rbenv.env == "system"
  tags:
    - rbenv

- name: install ruby {{ rbenv.ruby_version }} for system
  shell: bash -lc "rbenv install {{ rbenv.ruby_version }}"
  when:
    - rbenv.env == "system"
    - ruby_installed.rc != 0
  tags:
    - rbenv

- name: check if current system ruby version is {{ rbenv.ruby_version }}
  shell: $SHELL -lc "rbenv version | cut -d ' ' -f 1 | grep -Fx '{{ rbenv.ruby_version }}'"
  register: ruby_selected
  changed_when: false
  ignore_errors: yes
  always_run: yes
  when: rbenv.env == "system"
  tags:
    - rbenv

- name: set ruby {{ rbenv.ruby_version }} for system
  shell: bash -lc "rbenv global {{ rbenv.ruby_version }} && rbenv rehash"
  when:
    - rbenv.env == "system"
    - ruby_selected.rc != 0
  tags:
    - rbenv
