- name: clone the app
  git: dest={{ app_path }}
       repo={{ app_repo }}
       version="task/establish_front_end"
       accept_hostkey=true
       force=yes

- name: Check if there are commited changes on master
  command: bash -lc "git fetch origin && git diff --name-only origin/master"
  args:
    chdir: "{{app_path}}"
  register: changes_on_remote

- name: Inform User if there are no changes
  debug: msg="no changes"
  when: changes_on_remote.stdout_lines == []

- name: Detect package.json
  command: chdir={{ app_path }}
    bash -lc "test -e package.json"
  register: npm_result
  ignore_errors: true

- name: NPM install
  when: app_repo is defined and npm_result|success
  command: chdir={{ app_path }}
    bash -lc "npm install"

- name: Build FE
  command: chdir={{ app_path }}
    bash -lc "npm build"
