- name: Add Nginx Repository
  apt_repository: repo='ppa:nginx/stable' state=present
  register: ppastable

- name: Install Nginx
  apt: pkg=nginx state=installed update_cache=true
  when: ppastable|success

- name: Configure App nginx
  template: src=nginx_unicorn.j2 dest=/etc/nginx/sites-enabled/{{ app_name }}

- name: restart nginx
  command: bash -lc "sudo service nginx restart"
