---
- name: apt-get update upgrade
  apt: update_cache=yes  upgrade=safe
  tags: [update, upgrade]

- name: Install vim
  apt: name=vim state=present

- name: Install git
  apt: name=git-core state=present

- name: Create app path
  file: path={{ app_path }} state=directory mode=0755
